### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-intermedia-Analo-pez#1]
Muy buen trabajo @Analo-pez!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 207 / 347
- [x] CARPETAS > IMG: Los ficheros de imágenes deben empezar por `./images/` o `./img/`.
- [x] HTML > LINK: Debemos tener dos ficheros de estilos importados con un `link`.
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos.
- [x] CSS > COLOR: El color de los enlaces debe ser #4a4a4a
- [x] CSS > FONT-FAMILY: Es recomendable que la fuente del body sea Rubik para aprovechar la herencia.
- [x] CSS > FONT-FAMILY: La fuente del h1 debe ser Rubik
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.
- [x] CSS > FIXED: La cabecera debe estar fija en la parte superior de la página y con `top: 0`.
- [x] CSS > FIXED: La cabecera debe medir todo el ancho de la página.
- [x] CSS > CLASES: No se deben utilizar etiquetas CSS ni ids como selectores, salvo `a`, `html` y `body`.
- [x] CSS > CLASES: El fichero CSS no es correcto. Comprueba si has cerrado todas las llaves.
- [x] CSS > FLEX: El texto Creando diversidad digital debe estar centrado horizontal y verticalmente, lo mejor es hacerlo con flex.
- [x] CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha .

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te enjaca dímelo cuanto antes por favor.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by Analo-pez** [comment]
@migueldelmazo me ha generado duda lo de poner los links del color que se especifica, creo que he hecho lo que se pedía...
Si me lo pudieras confirmar (con la calma, que sé que no es urgente) te lo agradecería!!
